import os
import json
import boto3
from botocore.exceptions import ClientError

SECRET_NAME = "ScalarPlanckConfig"
REGION_NAME = "us-east-1"
LOCALSTACK_ENDPOINT = "http://localhost:4566"

def get_secret():
    # If IS_LOCAL is false, use live AWS credentials. Else use LocalStack.
    is_local = os.getenv("IS_LOCAL", "true").lower() == "true"

    if is_local:
        print(f"🔄 Fetching secrets from LocalStack ({LOCALSTACK_ENDPOINT})...")
        session = boto3.session.Session()
        client = session.client(
            service_name='secretsmanager',
            region_name=REGION_NAME,
            endpoint_url=LOCALSTACK_ENDPOINT,
            aws_access_key_id="test",
            aws_secret_access_key="test"
        )
    else:
        print(f"🔄 Fetching secrets from LIVE AWS Secrets Manager ({REGION_NAME})...")
        session = boto3.session.Session()
        client = session.client(
            service_name='secretsmanager',
            region_name=REGION_NAME
        )

    try:
        response = client.get_secret_value(SecretId=SECRET_NAME)
    except ClientError as e:
        print(f"❌ Failed to retrieve secret '{SECRET_NAME}': {e}")
        return None

    if 'SecretString' in response:
        return json.loads(response['SecretString'])
    else:
        import base64
        return json.loads(base64.b64decode(response['SecretBinary']))

def generate_env_files(secrets):
    if not secrets:
        print("❌ No secrets to write.")
        return

    # 1. Generate Backend .env
    backend_env_path = os.path.join(os.path.dirname(__file__), "backend", ".env")
    with open(backend_env_path, "w") as f:
        f.write("# Auto-generated by config_manager.py\n")
        f.write("# DO NOT COMMIT THIS FILE\n\n")
        for key, value in secrets.items():
            f.write(f"{key}={value}\n")
    print(f"✅ Generated backend config: {backend_env_path}")

    # 2. Generate Frontend .env.local
    frontend_env_path = os.path.join(os.path.dirname(__file__), "frontend", ".env.local")
    with open(frontend_env_path, "w") as f:
        f.write("# Auto-generated by config_manager.py\n")
        f.write("# DO NOT COMMIT THIS FILE\n\n")
        for key, value in secrets.items():
            # For Next.js to expose to browser, prepend NEXT_PUBLIC_ if it's safe/needed
            # For simplicity, we are passing all config explicitly prefixed 
            # to be used by the frontend config manager
            f.write(f"NEXT_PUBLIC_{key}={value}\n")
    print(f"✅ Generated frontend config: {frontend_env_path}")

if __name__ == "__main__":
    print("🚀 Starting Config Synchronizer...")
    secrets = get_secret()
    if secrets:
        generate_env_files(secrets)
        print("🎉 Configuration sync complete!")
