// Configuration Manager for Frontend
// This maps the NEXT_PUBLIC_* environment variables (generated by python config_manager.py)
// so the rest of the application can import these safely and cleanly.

const config = {
  POLY_API_KEY: process.env.NEXT_PUBLIC_POLY_API_KEY || '',
  POLY_API_SECRET: process.env.NEXT_PUBLIC_POLY_API_SECRET || '',
  POLY_API_PASSPHRASE: process.env.NEXT_PUBLIC_POLY_API_PASSPHRASE || '',
  PAPER_TRADING: process.env.NEXT_PUBLIC_PAPER_TRADING === 'True',
  LOG_LEVEL: process.env.NEXT_PUBLIC_LOG_LEVEL || 'INFO',
  MOCK_AUTH: process.env.NEXT_PUBLIC_MOCK_AUTH === 'true',
  GOOGLE_CLIENT_ID: process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID || '',
  FRONTEND_URL: process.env.NEXT_PUBLIC_FRONTEND_URL || 'http://localhost:3000',
  USER_POOL_ID: process.env.NEXT_PUBLIC_USER_POOL_ID || '',
  USER_POOL_CLIENT_ID: process.env.NEXT_PUBLIC_USER_POOL_CLIENT_ID || '',
  DYNAMODB_TABLE: process.env.NEXT_PUBLIC_DYNAMODB_TABLE || 'ScalarUsers',
  TRADES_TABLE: process.env.NEXT_PUBLIC_TRADES_TABLE || 'ScalarTrades',
};

export default config;
